# Page settings

baseURL = "https://ernest.guevarra.io/resume/"
publishDir = "docs"
languageCode = "en"
title = "Ernest Guevarra Résumé"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-118912078-2"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]





[params]
    author = ""
    description = ""


    primaryColor = "#A41034"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ernest Guevarra"
        tagline = "Public Health Specialist, Spatial Epidemiologist, R Developer"
        avatar = "guevarra.jpg"







    [params.contact]
        enable = true
        location = "Oxford, United Kingdom"

        [[params.contact.list]]
        icon = "fab fa-skype"
        url = "skype:ernestguevarra?call"
        text = "ernestguevarra"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ernest@guevarra.io"
        text = "ernest@guevarra.io"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ernest.guevarra.io"
        text = "https://ernest.guevarra.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Analytical"
        [[params.skills.list.items]]
        details = "Impact evaluation"
        [[params.skills.list.items]]
        details = "Coverage assessment"
        [[params.skills.list.items]]
        details = "Study/survey design"
        [[params.skills.list.items]]
        details = "Statistical analysis"
        [[params.skills.list.items]]
        details = "Geospatial analysis"

        [[params.skills.list]]
        title = "R"
        [[params.skills.list.items]]
        details = "Package development"
        [[params.skills.list.items]]
        details = "Shiny app development and deployment"
        [[params.skills.list.items]]
        details = "Analytic workflow development"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Public Health"
        university = "Harvard School of Public Health"
        dates = "2004 - 2005"
        [[params.education.list]]
        degree = "Doctor of Medicine"
        university = "University of the Philippines"
        dates = "1994 - 2001"
        [[params.education.list]]
        degree = "BSc in Basic Medical Sciences"
        university = "University of the Philippines"
        dates = "1994 - 1998"







    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Dr. Fang-Ching Sun Memorial Award"
        body = "Harvard School of Public Health"
        date = "2005"
        [[params.awards.list]]
        name = "Reebok Human Rights Award"
        body = "Reebok Foundation"
        date = "2003"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Filipino"
        level = "Native"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "I have more than 15 years of professional experience in community and public health in humanitarian crises and developing country-settings, including as a community health worker, medical doctor, and currently as specialised expert and head of metrics, analytics and technology for Valid International. I have expertise in spatial epidemiology, geo-statistics, and statistical programming using R. In my role as Head of Measures, I lead the design, development and implementation of innovative surveys and assessments on health and nutrition and bespoke analytical approaches that leverage the advantages of Bayesian statistics and resampling techniques."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Head of Measures"
        dates = "2017 - Present"
        company = "Valid International Ltd"
        details = "Leads design, development and implementation of innovative approaches, techniques and products for surveys and assessments focusing on health and nutrition for purposes of programme monitoring and evaluation, impact assessment, programme coverage and access or any other metric/indicator estimation. Leads the design and development of bespoke analytical techniques and the accompanying programming scripts and workflows for estimating various metrics/indicators, specifically leveraging Bayesian statistics, resampling approaches and Monte Carlo methods. Trains and supervises a team of 5 survey technicians and data analysts."

        [[params.experience.list]]
        title = "Surveys and Assessments Specialist"
        dates = "2015 - 2017"
        company = "Valid International Ltd"
        details = "Led Valid International’s Community-based Management of Acute Malnutrition (CMAM) coverage assessment team and has conducted coverage surveys in Somalia, Kenya, Ethiopia, Zambia, Nigeria, Niger, India and Ghana. Pioneered the design and development of specially designed methods to assess CMAM coverage such as Semi-Quantitative Evaluation of Access and Coverage (SQUEAC) and Simplified Lot Quality Assurance Sampling Evaluation of Access and Coverage (SLEAC). Co-developed a spatial sampling technique called Simple Spatial Sampling Method (S3M) for use in large-scale multi-indicator surveys that reports and maps indicator results at high spatial resolution at a national or regional level. Co-developed a low-cost, rapid assessment method for assessing nutritional status of children, women and elderly."

        [[params.experience.list]]
        title = "Technical Advisor"
        dates = "2010 - 2015"
        company = "Valid International Ltd"
        details = "Provided technical support and evaluation of nutrition programmes for the treatment of severe and moderate acute malnutrition. Worked on all areas related to the design and implementation of CMAM programmes, including: identification of barriers to health services; establishment of outpatient clinics in local health centres; case-finding; advice on logistics of community outreach programmes; advice on integration of systems with local, regional and national ministry of health programmes; training programmes for partner NGOs and local ministry of health medical and logistics staff; support and evaluation of programme systems including community outreach, case-finding, programme admission, triage and referral, discharge, case follow up and patient recording systems; establishment of stabilisation centres within hospitals; and evaluation of nutrition programmes at all stages."

        [[params.experience.list]]
        title = "Trainee"
        dates = "2009 - 2010"
        company = "Valid International Ltd"
        details = "Supported the lead consultants and experts in the setup, monitoring and evaluation of community-based manageement of acute malnutrition (CMAM) programmes in various countries."

        [[params.experience.list]]
        title = "Child Protection Advisor"
        dates = "2007 - 2008"
        company = "Save the Children in Sri Lanka"
        details = "Responsible for technical advice and practical field level lead, and mentoring to the project teams; District level liaison on project-related matters with UNICEF and other stakeholders in districts of coverage; Supporting project teams in documentation of project experiences and timely reports; Directly handle cases of children in need of special protection in liaison with UNICEF; Participate in assessments for closing of cases; and Training of field level project teams on handling children associated with armed groups."

        [[params.experience.list]]
        title = "Emergency Focal Point"
        dates = "2007"
        company = "UNICEF Somalia"
        details = "Direct emergency preparedness and response in the central south zone of Somalia; Manage emergency assessments in areas relevant to UNICEF’s core commitments to children specifically in the areas of child protection and HIV/AIDS; Ensure systems and actions are in place to meet UNICEF’s core commitments to children; Liaise with local UNICEF partners and provide technical support to their activities; Ensure regular communication between central south zone team and the rest of the section and the Emergency Management Team (EMT); Support monitoring and evaluation of activities; Provide regular updates and assessments on situation in the zone and its impact on activities."

        [[params.experience.list]]
        title = "Psychosocial Coordinator"
        dates = "2005 - 2006"
        company = "International Rescue Committee"
        details = "Oversee the strengthening of IRC Uganda’s psychosocial program activities integrating them into other key activities such as economic development, HIV/AIDS, and community dialogue/peace building; Conduct trainings and other capacity building activities for IRC’s local partners; Developing innovative ways to access remote communities, with a view to supporting community structures for promoting the safe, healthy and sustainable reintegration of former abductees into their communities of origin; Ensure conduct of regular follow up on former abductees, monitoring their reintegration process; Ensure community and peer support networks are promoting the process of reintegration; Examine degree to which IRC’s psychosocial programs are implemented and monitored in a participatory and community-based manner and recommend/implement improvements."

        [[params.experience.list]]
        title = "Community Organiser and Project Manager"
        dates = "2002 - 2004"
        company = "Balik Kalipay"
        details = "Implementation of a psychosocial support program for children through training and debriefing of teacher and youth volunteers and facilitation and organization of community support and participation; Supervision of staff community trainers; Provision of emergency medical and psychiatric services; Project evaluation; Project management – administrative and financial oversight."









    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Nutriverse"
        meta = "Open Source"
        tagline = "The nutriverse is a collection of tools and guides developed in R for use in nutrition and nutrition-related data collection and analysis. The nutriverse is for anyone who works with nutrition and nutrition-related data be that in collection, processing and analysis."

        [[params.projects.list]]
        title = "RapidSurveys"
        meta = "Open Source"
        tagline = "RapidSurveys develops methods and tools that facilitate robust and efficient health and nutrition surveys data collection, analysis and reporting."

        [[params.projects.list]]
        title = "SpatialWorks"
        meta = "Open Source"
        tagline = ""










    [params.publications]
        enable = true

        [[params.publications.list]]
        title = "Papers"
        [[params.publications.list.items]]
        details = "2018 · Impact evaluation of the World Food Programme’s moderate acute malnutrition treatment and prevention programmes in Sudan"
        [[params.publications.list.items]]
        details = "2016 · Assessing program coverage of two approaches to distributing a complementary feeding supplement to infants and young children in Ghana"
        [[params.publications.list.items]]
        details = "2016 · Household coverage of fortified staple food commodities in Rajasthan, India"
        [[params.publications.list.items]]
        details = "2012 · Semi-Quantitative Evaluation of Access and Coverage (SQUEAC)/simplified lot quality assurance sampling evaluation of access and coverage (SLEAC) technical reference"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/ernestguevarra"
        title = "ernestguevarra"
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/ernestguevarra"
        title = "ernestguevarra"
        #[[params.social.list]]
        #icon = "fab fa-twitter-square"
        #title = "@ernestguevarra"
        #url = "//twitter.com/ernestguevarra"





